import '../img/sailing.jpeg'
import '../img/frigate.jpeg'
import '../img/frigate2.jpeg'
import '../img/sailing-boat.png'
import '../img/hull_empty.png';
import '../img/hull_iron.png';
import '../img/hull_steel.png';
import '../img/hull_black.png';
import '../img/hull_mithril.png';
import '../img/hull_adamant.png';
import '../img/hull_rune.png';
import '../img/hull_dragon.png';
