name: Build and Deploy Mod to Mod.io

on:
  workflow_dispatch:
  # runs when you either create a new tag or push an existing one
  create:

jobs:
  build-deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to create a release

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0
      - run: git fetch --tags --force
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          check-latest: true

      - name: Build
        run: |
          npm install
          npm run dist

      - name: Extract metadata
        id: metadata
        run: |
          GAME_ID=$(jq '.game' metadata.json)
          MOD_ID=$(jq '.mod' metadata.json)
          VERSION=$(jq '.version' metadata.json -r)
          ZIPFILE_NAME=$(jq '.zipfile' metadata.json -r)
          VERSION_CHANGELOG=$(git log $(git describe --tags --abbrev=0 @^)..@ --pretty=%B)

          echo "GAME=$GAME_ID" >> $GITHUB_OUTPUT
          echo "MOD=$MOD_ID" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "ZIPFILE=./package/$ZIPFILE_NAME" >> $GITHUB_OUTPUT
          echo "CHANGELOG<<EOF"$'\n'"$VERSION_CHANGELOG"$'\n'EOF >> $GITHUB_OUTPUT

      - name: Deploy to mod.io
        uses: nickelc/upload-to-modio@v2.1.0
        with:
          token: ${{ secrets.MODIO_TOKEN }}
          game: ${{ steps.metadata.outputs.GAME }}
          mod: ${{ steps.metadata.outputs.MOD }}
          version: ${{ steps.metadata.outputs.VERSION }}
          path: ${{ steps.metadata.outputs.ZIPFILE }}
          changelog: ${{ steps.metadata.outputs.CHANGELOG }}
          active: true

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.metadata.outputs.ZIPFILE }}
          body: ${{ steps.metadata.outputs.CHANGELOG }}
          tag: v${{ steps.metadata.outputs.VERSION }}
          makeLatest: true
